---
title: "git_01"
author: "Math_115"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

Take this kiss upon the brow!  
And, in parting from you now,  
Thus much let me avow —  
You are not wrong, who deem  
That my days have been a dream;  
Yet if hope has flown away  
In a night, or in a day,  
In a vision, or in none,  
Is it therefore the less gone?   
All that we see or seem  
Is but a dream within a dream.  
  
I stand amid the roar  
Of a surf-tormented shore,  
And I hold within my hand  
Grains of the golden sand —  
How few! yet how they creep  
Through my fingers to the deep,  
While I weep — while I weep!   
O God! Can I not grasp  
Them with a tighter clasp?  
O God! can I not save  
One from the pitiless wave?  
Is all that we see or seem   
But a dream within a dream?  
